### ISSUE TITLE
No results and the error shows The error thread '<unnamed>' panicked at ...

### ISSUE THREAD

**Issue by a92932000** [alejandrogzi/gtfsort#7]
Hi Alejandro,

I have tried running the tool in multiple cores or single-core mode, and both results show errors as the below script.
I also try different ways to get the tools. eg install by cargo or Conda or using the container image in centos7/8.
How do I deal with this? 

```
$ gtfsort -t 1 -i TAIR10_GFF3_genes_transposons.gff -o sorted.gff 2>stderr.log


##### GTFSORT #####
A rapid chr/pos/feature gtf sorter in Rust.
Repo: github.com/alejandrogzi/gtfsort

2024-03-01T03:15:25.131Z INFO  [gtfsort] Using 1 threads
$ head stderr.log

thread '<unnamed>' panicked at /home/public_tools/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/public_tools/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf.rs:34:67:
called `Result::unwrap()` on an `Err` value: Invalid
thread '<unnamed>' panicked at /home/public_tools/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid
thread '<unnamed>' panicked at /home/public_tools/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid
thread '<unnamed>' panicked at /home/public_tools/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
```

By the way, I need to install it using Conda with an additional channel "conda-forge" for libgcc-ng.

```
$ conda create -n gtfsort -c bioconda gtfsort
WARNING: A conda environment already exists at '/home/tcman/miniconda3/envs/gtfsort'
Remove existing environment (y/[n])? y

Channels:
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides libgcc-ng >=12 needed by gtfsort-0.2.1-h4ac6f70_0

Could not solve for environment specs
The following package could not be installed
└─ gtfsort is not installable because it requires
   └─ libgcc-ng >=12 , which does not exist (perhaps a missing channel).
```
```
$ conda create -n gtfsort -c bioconda gtfsort -c conda-forge
Channels:
 - bioconda
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/tcman/miniconda3/envs/gtfsort

  added / updated specs:
    - gtfsort


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  gtfsort            bioconda/linux-64::gtfsort-0.2.1-h4ac6f70_0
  libgcc-ng          conda-forge/linux-64::libgcc-ng-13.2.0-h807b86a_5
  libgomp            conda-forge/linux-64::libgomp-13.2.0-h807b86a_5
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-13.2.0-h7e041cc_5


Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate gtfsort
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

**Comment by alejandrogzi** [comment]
Hi @a92932000 

Thank you for using gtfsort!

The problem you are encountering is due to the compatibility of your input files with gtfsort (your error is produced because gtfsort could not parse the attributes, the parsing logic was intended to work only with GTFs). This tool only accepted GTF files until v.0.2.1, not GFF support. Coincidentally, yesterday I started working on the new version (v.0.2.2) with GFF support. This version has been published a few minutes ago, so probably now you won't have any problem sorting your files. 

Please be aware that using conda at this time will cause the same error (usually takes 1-2 days for the conda bot to update the new recipe). You still have plenty of options: 1) cargo install gtfsort; 2) build from source (git clone and then cargo run --release -- ...); 3) docker, just follow the repo README instructions. 

Please reach out if you still have problems. If so, please share your .gff file.

Hope this helped,
Alejandro

**Comment by a92932000** [comment]
Hi Alejandro

Thank you update for supporting gff file.
I try the new version 0.2.2, but it does not work well for this gff file.
The file "TAIR10_GFF3_genes.gff" is downloaded from the TAIR10 (Arabidopsis) website. Arabidopsis is a model plant.
https://www.arabidopsis.org/download/index-auto.jsp?dir=%2Fdownload_files%2FGenes%2FTAIR10_genome_release%2FTAIR10_gff3

Below is my test run results.
```
$ head TAIR10_GFF3_genes.gff
Chr1    TAIR10  chromosome      1       30427671        .       .       .       ID=Chr1;Name=Chr1
Chr1    TAIR10  gene    3631    5899    .       +       .       ID=AT1G01010;Note=protein_coding_gene;Name=AT1G01010
Chr1    TAIR10  mRNA    3631    5899    .       +       .       ID=AT1G01010.1;Parent=AT1G01010;Name=AT1G01010.1;Index=1
Chr1    TAIR10  protein 3760    5630    .       +       .       ID=AT1G01010.1-Protein;Name=AT1G01010.1;Derives_from=AT1G01010.1
Chr1    TAIR10  exon    3631    3913    .       +       .       Parent=AT1G01010.1
Chr1    TAIR10  five_prime_UTR  3631    3759    .       +       .       Parent=AT1G01010.1
Chr1    TAIR10  CDS     3760    3913    .       +       0       Parent=AT1G01010.1,AT1G01010.1-Protein;
Chr1    TAIR10  exon    3996    4276    .       +       .       Parent=AT1G01010.1
Chr1    TAIR10  CDS     3996    4276    .       +       2       Parent=AT1G01010.1,AT1G01010.1-Protein;
Chr1    TAIR10  exon    4486    4605    .       +       .       Parent=AT1G01010.1
$ gtfsort -t 1 -i TAIR10_GFF3_genes.gff -o sorted.gff 2>stderr.log

##### GTFSORT #####
The fastest chr/pos/feature GTF/GFF sorter you'll see.
Repo: github.com/alejandrogzi/gtfsort
Feel free to contact the developer if any issue/bug is found.

Version: 0.2.2
2024-03-02T12:37:37.136Z INFO  [gtfsort] Using 1 threads
$ head stderr.log
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
called `Result::unwrap()` on an `Err` value: MissingGeneId("ID=Chr1;Name=Chr1")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
called `Result::unwrap()` on an `Err` value: MissingGeneId("Parent=AT1G34260.1,AT1G34260.1-Protein;")
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
called `Result::unwrap()` on an `Err` value: MissingGeneId("Parent=AT1G51430.1,AT1G51430.1-Protein;")
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
called `Result::unwrap()` on an `Err` value: MissingGeneId("Parent=AT1G53345.1")
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
```
The gff file contains non-trancript features eg. chromosome, protein ...
```
cut -f 3 TAIR10_GFF3_genes.gff | sort -u
CDS
chromosome
exon
five_prime_UTR
gene
miRNA
mRNA
mRNA_TE_gene
ncRNA
protein
pseudogene
pseudogenic_exon
pseudogenic_transcript
rRNA
snoRNA
snRNA
three_prime_UTR
transposable_element_gene
tRNA
```

Simplify gff file by gffread
```
$ gffread -F --keep-genes -o TAIR10_GFF3_genes.gffread.gff TAIR10_GFF3_genes.gff
$ head TAIR10_GFF3_genes.gffread.gff
##gff-version 3
# gffread v0.12.7
# gffread -F --keep-genes -o TAIR10_GFF3_genes.gffread.gff TAIR10_GFF3_genes.gff
Chr1    TAIR10  gene    3631    5899    .       +       .       ID=AT1G01010;Note=protein_coding_gene;Name=AT1G01010
Chr1    TAIR10  mRNA    3631    5899    .       +       .       ID=AT1G01010.1;Parent=AT1G01010;Name=AT1G01010.1;Index=1
Chr1    TAIR10  exon    3631    3913    .       +       .       Parent=AT1G01010.1
Chr1    TAIR10  exon    3996    4276    .       +       .       Parent=AT1G01010.1
Chr1    TAIR10  exon    4486    4605    .       +       .       Parent=AT1G01010.1
Chr1    TAIR10  exon    4706    5095    .       +       .       Parent=AT1G01010.1
Chr1    TAIR10  exon    5174    5326    .       +       .       Parent=AT1G01010.1
$ cut -f 3 TAIR10_GFF3_genes.gffread.gff | sort -u
CDS
exon
gene
# gffread -F --keep-genes -o TAIR10_GFF3_genes.gffread.gff TAIR10_GFF3_genes.gff
# gffread v0.12.7
##gff-version 3
miRNA
mRNA
mRNA_TE_gene
ncRNA
pseudogene
pseudogenic_transcript
rRNA
snoRNA
snRNA
transposable_element_gene
tRNA
```

Sort the processed gff file
```
$ gtfsort -t 1 -i TAIR10_GFF3_genes.gffread.gff -o sorted.gffread.gff 2>stderr.gffread.log

##### GTFSORT #####
The fastest chr/pos/feature GTF/GFF sorter you'll see.
Repo: github.com/alejandrogzi/gtfsort
Feel free to contact the developer if any issue/bug is found.

Version: 0.2.2
2024-03-02T12:39:52.093Z INFO  [gtfsort] Using 1 threads
$ head stderr.gffread.log
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
called `Result::unwrap()` on an `Err` value: MissingGeneId("ID=AT1G01010;Note=protein_coding_gene;Name=AT1G01010")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
called `Result::unwrap()` on an `Err` value: MissingGeneId("Parent=AT1G35030.1")
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
called `Result::unwrap()` on an `Err` value: MissingGeneId("Parent=AT1G51400.1")
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
called `Result::unwrap()` on an `Err` value: MissingGeneId("Parent=AT1G53310.1")
thread '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
```

**Comment by alejandrogzi** [comment]
@a92932000,

Thanks for the detailed log info! It seems that the problem comes from your file. 

```
thread` '<unnamed>' panicked at /home/tcman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.2/src/gtf.rs:25:67:
called `Result::unwrap()` on an `Err` value: MissingGeneId("ID=AT1G01010;Note=protein_coding_gene;Name=AT1G01010")
```

That indicates that an error occurred while parsing attributes from a given line, in this case: 

```
ID=AT1G01010;Note=protein_coding_gene;Name=AT1G01010
``` 

Both, GTF and GFF modes, support files that follow a kind of "base" structure (e.g. GENCODE/Ensembl) with only 3 mandatory attributes: "gene_id" (mandatory for all lines), "transcript_id" (mandatory for all transcript and the rest of lines) and "exon_number" (mandatory for exons, CDS, etc). This is an example of a "gene" line from a GENCODE GFF:

```
chr1    HAVANA  gene    11869   14409   .       +       .       ID=ENSG00000290825.1;gene_id=ENSG00000290825.1;gene_type=lncRNA;gene_name=DDX11L2;level=2;tag=overlaps_pseudogene
```

Note that:

```
gene_id=ENSG00000290825.1
```

is present, the rest of things actually do not matter.

Why is it like that? The inputs to the algorithm are based on Hash layers build from your GFF file. By default genes and trascripts are taken as the sources for the outer layers while the rest of features are considered "childs". This is how gtfsort no only sorts by chromosome and position but by features (trying to make it more easier to look at). 

Your GFF seems to coming from a custom source, so probably this is why it is like that and gtfsort fails. Sorry for not being of help here. 

Best,
Alejandro

**Comment by a92932000** [comment]
Hi Alejandro,

I understand the issue results from losing "gene_id". Thank you quick reply. 
However, my study heavily relies on arabidopsis. I will write my program to sort it.

By the way,
I think that only ID and parent are required for gene and transcript/mRNA features in gff3 format based on Sequence Ontology.
https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md
I have tried the Arabidopsis gff file from Ensembl plant, but it still did not work.

Thank your help
